import {SUBJECTS,loadCatalog,loadGame} from './platform/catalog.js';
import * as Progress from './platform/progress.js';
import * as Growth from './platform/growth.js';

const app=document.querySelector('#app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const AWARDS=[{stars:30,emoji:'🌱',name:'호기심 새싹'},{stars:100,emoji:'🌼',name:'발견의 꽃'},{stars:250,emoji:'🦋',name:'생각 나비'},{stars:500,emoji:'👑',name:'배움의 요정'}];
const REFLECTIONS={math:'어떤 방법으로 셌는지 엄마 아빠에게 알려 줄까?',korean:'오늘 배운 낱말로 우리 가족 이야기를 만들어 볼까?',english:'오늘 만난 영어 단어를 집에서 찾아볼까?'};
let catalog=[],filter='all',currentGame=null,view='home',error='',modal=null,lastFocus=null,loading=false,showAll=false;
let loadGeneration=0,roundOwner=null;
const currentLearner=()=>Progress.LEARNERS[Progress.learner()];
const published=()=>catalog.filter(g=>g.status==='published');
const overview=()=>Progress.summary(catalog);
const currentRound=()=>currentGame?Progress.gameProgress(currentGame.id).round:null;
const currentQuestion=()=>{const r=currentRound();return r&&currentGame.questions.find(q=>q.id===r.ids[r.index]);};
function stopSound(){if('speechSynthesis'in window)window.speechSynthesis.cancel();}
function move(next){loadGeneration++;loading=false;stopSound();view=next;error='';render();window.scrollTo({top:0,behavior:'instant'});document.querySelector('main h1,main h2')?.focus({preventScroll:true});}
function header(){const p=currentLearner();return `<header class="header"><button class="brand" data-action="home" aria-label="반짝 배움터 처음으로"><span class="brand-star" aria-hidden="true">✦</span><span><small>TAEHEE & SEHEE</small>반짝 배움터</span></button><nav class="nav" aria-label="주 메뉴">${[['home','놀이 고르기'],['growth','성장 지도'],['collection','나의 별']].map(([id,label])=>`<button data-action="${id}" class="${view===id?'active':''}" ${view===id?'aria-current="page"':''}>${label}</button>`).join('')}</nav><div class="user-controls"><span class="header-star" aria-label="모은 별 ${overview().stars}개">⭐ ${overview().stars}</span><button class="profile-button" data-action="profiles" aria-label="아이 바꾸기, 현재 ${p.name}"><span class="profile-avatar" aria-hidden="true">${p.emoji}</span>${p.name}</button></div></header>`;}
function footer(){return `<footer class="footer"><span>태희와 세희, 발견하는 즐거움 ✦</span><button data-action="parents">보호자 안내</button></footer>`;}
function gameCard(g){const record=overview().games.find(r=>r.id===g.id),rec=g.growth?Growth.recommendation(g.subject,catalog):null;return `<article class="game-card ${g.subject}"><div class="game-top"><div class="game-icon" aria-hidden="true">${esc(g.emoji)}</div><span class="subject-label">${SUBJECTS[g.subject].name}</span></div><h3>${esc(g.title)}</h3><p class="game-desc">${esc(g.description)}</p><div class="game-meta"><span>${esc(g.levelLabel)}</span><span>${g.questionCount}문제</span></div>${g.kind==='external'?`<a class="game-launch" href="${esc(g.url)}" data-external="${g.id}">${record.resume?'이어서 놀기':'놀러 가기'}</a>`:`<button class="game-launch" data-action="play" data-game="${g.id}" ${loading?'disabled':''}>${record.resume?'이어서 놀기':rec?.reviewDue?'다시 만나기':'시작하기'}</button>`}<p class="game-progress">${record.started?`⭐ ${record.stars} · ${record.mastered}개의 발견`:`한 번에 ${g.kind==='external'?5:currentLearner().roundSize}문제 · 천천히 해도 돼`}</p>${rec&&rec.stage===g.stage&&rec.action==='advance'?`<button class="next-challenge" data-action="stage" data-subject="${g.subject}" data-stage="${rec.suggestedStage}">🌟 다음 단계 만나기</button>`:''}${rec&&rec.stage===g.stage&&rec.action==='practice'?`<button class="next-challenge" data-action="stage" data-subject="${g.subject}" data-stage="${rec.suggestedStage}">🌱 쉬운 그림부터 다시</button>`:''}</article>`;}
function home(){const sum=overview(),next=AWARDS.find(a=>a.stars>sum.stars),games=published().filter(g=>(filter==='all'||g.subject===filter)&&(showAll||(g.growth&&g.stage===Growth.selectedStage(g.subject))));return `<section class="welcome compact"><div><div class="kicker">🌈 나만의 속도로, 한 걸음 더</div><h1 tabindex="-1">${currentLearner().name}야, <em>같이 발견해 볼까?</em></h1><p>${Progress.learner()==='se'?'듣고, 그림을 콕! 세 이야기로 놀자.':'생각하고, 말해 보고! 다섯 이야기로 놀자.'}</p></div><img class="welcome-art" src="./assets/fairy-companions.webp" width="246" height="220" alt="분홍 별 요정과 보라 달 요정"></section><section aria-labelledby="games-title"><div class="section-top"><div class="section-title"><h2 id="games-title">${showAll?'모든 놀이터':'오늘의 놀이'}</h2><button class="text-button browse-toggle" data-action="all-games">${showAll?'내 놀이만':'더 찾아보기'}</button></div><div class="filters" aria-label="과목 고르기">${Object.entries(SUBJECTS).map(([id,s])=>`<button class="filter" data-action="filter" data-subject="${id}" aria-pressed="${filter===id}">${s.emoji} ${s.name}</button>`).join('')}</div></div><div class="games-grid ${showAll?'':'recommended'}">${games.map(gameCard).join('')}</div></section><section class="path-teaser"><span aria-hidden="true">🌱 🌼 🍓</span><div><h2>조금씩 더 넓어지는 배움</h2><p>잘 알게 된 개념에서 다음 이야기로.</p></div><button class="secondary" data-action="growth">성장 지도 보기</button></section><section class="progress-strip"><span class="reward-icon" aria-hidden="true">${next?.emoji||'👑'}</span><div class="progress-copy"><h3>${next?`다음 선물은 ‘${next.name}’`:'배움의 요정이 되었어!'}</h3><p>${next?`별 ${next.stars-sum.stars}개가 더 모이면 만나요.`:'발견한 이야기가 함께 빛나요.'}</p><div class="meter" role="progressbar" aria-label="다음 선물까지 모은 별" aria-valuemin="0" aria-valuemax="${next?.stars||500}" aria-valuenow="${Math.min(sum.stars,next?.stars||500)}"><span style="width:${Math.min(100,sum.stars/(next?.stars||500)*100)}%"></span></div></div><button class="text-button" data-action="collection">모은 별 보기</button></section>`;}
function growth(){return `<section class="collection-head"><h1 tabindex="-1">${currentLearner().name}의 성장 지도</h1><p>지금의 놀이에서 다음 발견으로.</p></section><p class="map-intro">어른과 함께 골라요. 과목마다 출발점이 달라도 좋아요.</p>${['math','korean','english'].map(subject=>{const rec=Growth.recommendation(subject,catalog);return `<section class="path-panel"><h2>${SUBJECTS[subject].emoji} ${SUBJECTS[subject].name}</h2><div class="growth-path">${[1,2,3,4].map(stage=>{const st=Growth.STAGES[stage],g=published().find(g=>g.growth&&g.subject===subject&&g.stage===stage);if(!g)return '';return `<article class="stage-node ${stage===rec.stage?'selected':''}"><span class="stage-icon" aria-hidden="true">${st.emoji}</span><span class="stage-label">${stage===rec.stage?'지금의 놀이':stage===rec.suggestedStage&&rec.action==='advance'?'다음 도전':'언제든 탐험'}</span><h3>${esc(st.name)}</h3><p>${esc(g.description)}</p><button class="secondary" data-action="stage" data-subject="${subject}" data-stage="${stage}">${stage===rec.stage?'이어 배우기':'이 단계 고르기'}</button></article>`;}).join('')}</div><details class="evidence"><summary>보호자와 연습 기록 보기</summary><p>${esc(rec.reason)}</p><p>최근 풀이 ${rec.recentCount}개 · 서로 다른 정답 문항 ${rec.distinctCorrect}개 · 완료한 회차 ${rec.completedRounds}회${rec.accuracy!==null&&rec.recentCount?' · 최근 정답률 '+Math.round(rec.accuracy*100)+'%':''}</p><p>${rec.reviewDue?'지난 개념을 다시 만나 볼 때예요.':'충분히 생각하고 이유를 말해 본 뒤 다음 단계로 가요.'}</p></details></section>`;}).join('')}<section class="panel map-note"><h2>배우는 힘을 키우는 순서</h2><p>실물로 해 보기 → 그림으로 생각하기 → 말과 기호로 설명하기 → 새로운 이야기에 써 보기</p><p>단계는 이 앱 안의 연습 경로예요. 나이·학년·발달 진단 점수가 아니며, 다음 단계는 직접 선택해요.</p></section>`;}
function picture(q){const v=q.visual;if(!v)return '';
 if(v.kind==='groups')return `<div class="question-picture groups-picture" style="--group-count:${v.groups.length}">${v.groups.map(g=>`<div class="group-box"><p>${esc(g.label)}</p><div class="counter-group" role="img" aria-label="${esc(g.label)} ${g.count}개">${Array.from({length:g.count},()=>`<span aria-hidden="true">${esc(g.emoji)}</span>`).join('')}</div></div>`).join('')}</div>`;
 if(v.kind==='bars'){const max=Math.max(...v.bars.map(b=>b.value));return `<div class="question-picture bars-picture">${v.bars.map(b=>`<div><p>${esc(b.label)}</p><div class="measure-track"><span style="width:${b.value/max*100}%;background:${b.label.includes('분홍')?'#d967a1':b.label.includes('노란')?'#e5b638':b.label.includes('초록')?'#519f69':'#a986d4'}"></span></div></div>`).join('')}</div>`;}
 if(v.kind==='fraction')return `<div class="question-picture"><p class="fraction-label">${esc(v.label)}</p><div class="fraction-bar" role="img" aria-label="똑같이 나눈 ${v.parts}조각 중 색칠한 ${v.filled}조각">${Array.from({length:v.parts},(_,i)=>`<span class="${i<v.filled?'filled':''}"></span>`).join('')}</div></div>`;
if(v.kind==='counters'){
 if(v.operator==='-')return `<div class="question-picture"><div class="counter-group" style="margin:auto;max-width:440px" role="img" aria-label="${v.left}개 중 ${v.right}개를 빼는 그림">${Array.from({length:v.left},(_,i)=>`<span style="${i>=v.left-v.right?'opacity:.28;text-decoration:line-through;text-decoration-color:#715384':''}">${esc(v.emoji)}</span>`).join('')}</div><p class="counter-caption">처음 ${v.left}개에서 ${v.right}개를 빼 보자.</p></div>`;
 return `<div class="question-picture"><div class="counters" role="img" aria-label="${v.left}개와 ${v.right}개를 합치는 그림"><div class="counter-group">${Array.from({length:v.left},()=>`<span>${esc(v.emoji)}</span>`).join('')}</div><span class="operator">+</span><div class="counter-group">${Array.from({length:v.right},()=>`<span>${esc(v.emoji)}</span>`).join('')}</div></div><p class="counter-caption">두 무리를 하나씩 세어 보자.</p></div>`;
 }return `<div class="question-picture"><span class="${v.kind==='word'?'visual-word':'picture-emoji'}" ${v.kind==='emoji'?'aria-hidden="true"':''}>${esc(v.kind==='word'?v.text:v.emoji)}</span></div>`;}
function quiz(){const s=currentRound();if(!s)return '<section class="error"><h1>하던 놀이를 찾지 못했어요.</h1><button class="primary" data-action="home">놀이 고르기</button></section>';if(s.finished)return result();const q=currentQuestion();if(!q)return '<section class="error"><h1>새로 바뀐 놀이를 다시 시작해 주세요.</h1><button class="primary" data-action="home">놀이 고르기</button></section>';const a=s.answers[s.index];return `<div class="game-area"><div class="activity-head"><button class="back" data-action="home">배움터로</button><span class="activity-title">${esc(currentGame.title)}</span></div><div class="round-progress"><span>${s.index+1} / ${s.ids.length}</span><div class="steps" aria-label="${s.ids.length}문제 중 ${s.index+1}번째">${Array.from({length:s.ids.length},(_,i)=>`<span class="step ${i<s.index?'done':i===s.index?'current':''}"></span>`).join('')}</div><span>⭐ ${s.answers.reduce((n,a)=>n+a.earned,0)}</span></div><section class="panel"><div class="question-head"><div><p class="question-type">${SUBJECTS[currentGame.subject].emoji} ${SUBJECTS[currentGame.subject].name} 이야기</p><h1 tabindex="-1">${esc(q.title)}</h1></div>${'speechSynthesis'in window?'<button class="sound" data-action="read" aria-label="문제와 보기 읽어주기">🔊</button>':''}</div><p class="story">${esc(q.story)}</p>${picture(q)}${q.cue?`<button class="cue-button" data-action="cue">🔊 소리 듣기</button><p class="cue-fallback">함께 읽어 주세요: <span lang="${esc(q.cue.lang)}">${esc(q.cue.text)}</span></p>`:''}<h2 class="prompt">${esc(q.prompt)}</h2><div class="answers ${q.choiceMode==='picture'?'picture-answers':''}" aria-label="정답 고르기">${q.choices.map((choice,i)=>`<button class="answer ${a?(i===q.answer?'correct':i===a.choice?'wrong':''):''}" data-action="answer" data-choice="${i}" ${q.choiceLabels?`aria-label="${esc(q.choiceLabels[i])}"`:''} ${a?'disabled':''}><span class="answer-num">${a&&i===q.answer?'✓':i+1}</span><span ${currentGame.subject==='english'?'lang="en"':''}>${esc(choice)}</span></button>`).join('')}</div>${a?`<section class="feedback ${a.correct?'':'learn'}" id="feedback" tabindex="-1"><div class="feedback-head"><h2>${a.correct?'✨ 잘 찾았어!':'🌱 함께 알아보자!'}</h2><span class="earned">${a.earned?`⭐ +${a.earned}`:'복습 완료'}</span></div><div class="correct-answer" ${currentGame.subject==='english'?'lang="en"':''}>${esc(q.choices[q.answer])}</div>${q.explanation.map(t=>`<p>${esc(t)}</p>`).join('')}${'speechSynthesis'in window?'<button class="secondary" data-action="explain">🔊 해설 듣기</button>':''}${q.speak&&'speechSynthesis'in window?'<button class="english-sound" data-action="pronounce">🔊 영어로 듣고 따라하기</button>':''}<button class="primary" data-action="next">${s.index===s.ids.length-1?'모은 별 보기':'다음 이야기'}</button></section>`:''}<p class="voice-status" id="voice-status" role="status"></p></section>${!a?'<p class="subtle">시간 제한은 없어. 천천히 생각해 봐!</p>':''}</div>`;}
function result(){const r=currentRound(),right=r.answers.filter(a=>a.correct).length,stars=r.answers.reduce((n,a)=>n+a.earned,0);return `<div class="game-area"><section class="panel result"><div class="result-icon" aria-hidden="true">${right===r.ids.length?'🌟':'🌼'}</div><h1 tabindex="-1">${currentLearner().name}의 발견이 늘었어!</h1><p>${r.ids.length}개의 이야기를 만났네.<br>${right===r.ids.length?'새로운 생각이 반짝반짝!':'함께 배운 이야기도 소중해.'}</p><div class="result-stats"><div class="stat"><strong>⭐ +${stars}</strong><span>이번에 모은 별</span></div><div class="stat"><strong>${right} / ${r.ids.length}</strong><span>스스로 찾은 답</span></div></div><div class="conversation"><small>화면 밖에서도 놀자!</small>${esc(currentGame.offline||REFLECTIONS[currentGame.subject])}</div><button class="primary" data-action="home">다른 놀이 고르기</button><button class="text-button" data-action="collection">나의 별 보러 가기</button></section></div>`;}
function collection(){const sum=overview();return `<section class="collection-head"><h1 tabindex="-1">${currentLearner().name}의 별이 ${sum.stars}개!</h1><p>여러 놀이터의 발견을 한곳에 모았어.</p></section><div class="awards">${AWARDS.map(a=>`<article class="award ${sum.stars<a.stars?'locked':''}"><div class="award-icon" aria-hidden="true">${a.emoji}</div><h3>${a.name}</h3><p>${sum.stars>=a.stars?'✨ 나의 배움터에 도착!':`별 ${a.stars}개에 만나요`}</p></article>`).join('')}</div><section class="panel"><h2>놀이마다 차곡차곡</h2>${published().map(g=>{const r=sum.games.find(r=>r.id===g.id);return `<div class="record-row"><span>${esc(g.emoji)} ${esc(g.title)}</span><span class="count">${r.mastered} / ${g.questionCount}개의 발견</span><span class="stars">⭐ ${r.stars}</span></div>`;}).join('')}<p class="note">단위 정원에서 모은 별도 함께 보여요.<br>이 기기에서 같은 브라우저로 놀면 기록이 이어져요.</p></section>`;}
function render(){const content=error?`<section class="error"><h1 tabindex="-1">잠깐, 놀이를 확인할게.</h1><p>${esc(error)}</p><button class="primary" data-action="reload">다시 불러오기</button><button class="text-button" data-action="home">배움터로</button></section>`:view==='home'?home():view==='collection'?collection():view==='growth'?growth():quiz();app.innerHTML=header()+`<main class="shell" id="main">${!Progress.storageAvailable?'<div class="storage-warning" role="status">지금은 기록이 저장되지 않을 수 있어요. 보호자 안내에서 기록을 내보내 주세요.</div>':''}${content}</main>`+footer();}
async function launch(id){const entry=published().find(g=>g.id===id);if(!entry||entry.kind!=='quiz')throw new Error('시작할 놀이를 선택해 주세요.');const generation=++loadGeneration;const who=Progress.learner();loading=true;error='';render();document.querySelector('#announcer').textContent='놀이를 불러오고 있어요.';try{const game=await loadGame(entry);if(generation!==loadGeneration||who!==Progress.learner())return;currentGame={...game,title:entry.title};roundOwner=who;Progress.beginRound(currentGame);view='quiz';stopSound();render();window.scrollTo({top:0,behavior:'instant'});document.querySelector('main h1')?.focus({preventScroll:true});}catch(e){if(generation===loadGeneration){error=e.message;render();}}finally{if(generation===loadGeneration)loading=false;}return{game:id,view};}
function answer(choice){if(view!=='quiz'||!currentGame)return;if(roundOwner!==Progress.learner()){move('home');return;}const a=Progress.answerQuestion(currentGame,choice);if(!a)return;stopSound();render();document.querySelector('#feedback')?.focus({preventScroll:true});document.querySelector('#feedback')?.scrollIntoView({block:'nearest',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});document.querySelector('#announcer').textContent=a.correct?'맞았어요. 해설을 읽어봐요.':'해설과 함께 알아봐요.';}
function speak(mode='question'){const q=currentQuestion();if(!q||!('speechSynthesis'in window))return;const answered=currentRound()?.answers[currentRound().index];if(['answer','explain'].includes(mode)&&!answered)return;stopSound();let parts=[];if(mode==='answer'&&q.speak)parts=[q.speak];else if(mode==='cue'&&q.cue)parts=[q.cue];else if(mode==='explain')parts=[{text:q.explanation.join(' '),lang:'ko-KR'}];else {parts=[{text:q.readText||q.story+' '+q.prompt,lang:'ko-KR'}];if(q.cue)parts.push(q.cue);if(!q.readText)q.choices.forEach((c,i)=>{parts.push({text:`${i+1}번.`,lang:'ko-KR'},{text:q.choiceLabels?.[i]||c,lang:q.choiceLabels?'ko-KR':currentGame.subject==='english'?'en-US':'ko-KR'});});}for(const part of parts){const u=new SpeechSynthesisUtterance(part.text);u.lang=part.lang;u.rate=part.lang==='en-US'?0.72:0.82;u.onerror=()=>{const el=document.querySelector('#voice-status');if(el)el.textContent='음성이 들리지 않으면 어른이 문제와 보기를 읽어 주세요.';};window.speechSynthesis.speak(u);}}
function openModal(type){lastFocus=document.activeElement;modal=type;const dialog=document.createElement('div');dialog.className='overlay';dialog.id='modal';dialog.innerHTML=`<section class="dialog" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="dialog-head"><h2 id="modal-title">${type==='profiles'?'누구의 배움터로 갈까?':'보호자 안내'}</h2><button class="close" data-action="close" aria-label="닫기">×</button></div>${type==='profiles'?`<div class="profiles">${Object.entries(Progress.LEARNERS).map(([id,p])=>`<button class="profile-choice" data-action="select-profile" data-profile="${id}"><span aria-hidden="true">${p.emoji}</span>${p.name}<small>⭐ ${Progress.summary(catalog,id).stars}개</small></button>`).join('')}</div>`:`<div class="parent-text"><p><strong>하루 한 놀이부터</strong><br>태희는 5문제, 세희는 3문제씩 만납니다. 두 아이의 수준은 과목별 성장 지도에서 따로 고릅니다. 문장을 읽기 어려워하면 읽어주기를 사용하고, 아이가 생각한 이유를 말로 설명하게 해 주세요.</p><p><strong>별과 이해 기록을 따로</strong><br>새 문제를 스스로 맞히면 별 10개, 해설과 배우면 2개를 받습니다. 나중에 맞히면 8개를 더 받아요. 같은 문제는 최대 10개예요. 단위 정원의 기존 별도 합산합니다.</p><p><strong>기록은 현재 기기에 저장</strong><br>태희·세희 기록을 따로 보관합니다. 같은 기기·브라우저에서 이어집니다. 다른 기기에는 자동 동기화되지 않으며, 브라우저 데이터 삭제 시 사라질 수 있습니다. 아래 기능으로 모든 게임의 기록을 함께 옮길 수 있습니다.</p><div class="parent-actions"><button class="secondary" data-action="export">전체 기록 내보내기</button><button class="secondary" data-action="import">기록 가져오기</button></div><input type="file" id="import-file" accept="application/json,.json" hidden><p id="import-status" role="status" style="margin-top:12px"></p><p><strong>성장 추천의 기준</strong><br>새 단계의 서로 다른 문제를 충분히 만나고, 두 회차 이상에서 이해가 확인되면 다음 도전을 추천합니다. 별을 많이 모았거나 생일이 지났다는 이유로 진급하지 않습니다. 최근 8개 풀이의 80% 이상 정답과 서로 다른 6개 문항 정답을 사용합니다. 이 수치는 앱 운영 기준이며 검증된 발달 진단 기준이 아닙니다. 성장 지도에서 쉬운 단계나 다음 도전을 언제든 선택할 수 있습니다.</p><p><strong>짧은 놀이와 실제 경험</strong><br>세희는 보호자와 그림·듣기부터, 태희는 생각한 이유를 설명하기부터 시작해 보세요. 각 회차 뒤 실물 활동을 하나 제안합니다. 영어 출발점은 영어 경험에 맞춰 별도로 조정해 주세요.</p><p><strong>앞으로 자라는 배움터</strong><br>새 게임을 추가해도 아이별 기록과 보상을 함께 사용할 수 있도록 구성했습니다. 다음 주제는 아이들의 흥미와 어려워하는 개념을 보고 정하면 됩니다.</p><p>영어 듣기는 기기의 영어 음성을 사용합니다. 사용할 수 있는 음성은 기기마다 다를 수 있습니다.</p></div>`}</section>`;document.body.append(dialog);app.inert=true;document.body.style.overflow='hidden';dialog.querySelector('button').focus();}
function closeModal(){document.querySelector('#modal')?.remove();app.inert=false;document.body.style.overflow='';modal=null;lastFocus?.focus();}
function download(){const blob=new Blob([JSON.stringify(Progress.exportRecords(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='sparkle-learning-records-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('click',e=>{
 const external=e.target.closest('[data-external]');if(external){stopSound();Progress.selectLearner(Progress.learner());return;}
 const target=e.target.closest('[data-action]');if(!target)return;
 switch(target.dataset.action){case'home':move('home');break;case'collection':move('collection');break;case'growth':move('growth');break;case'all-games':showAll=!showAll;render();break;case'stage':{const subject=target.dataset.subject,stage=Number(target.dataset.stage);Growth.setStage(subject,stage);const entry=published().find(g=>g.growth&&g.subject===subject&&g.stage===stage);if(entry)void launch(entry.id);break;}case'filter':filter=target.dataset.subject;render();break;case'play':void launch(target.dataset.game);break;case'answer':answer(Number(target.dataset.choice));break;case'next':if(roundOwner!==Progress.learner()){move('home');break;}if(currentGame){stopSound();Progress.nextQuestion(currentGame.id);render();window.scrollTo({top:0,behavior:'instant'});document.querySelector('main h1')?.focus({preventScroll:true});}break;case'profiles':openModal('profiles');break;case'parents':openModal('parents');break;case'close':closeModal();break;case'select-profile':Progress.selectLearner(target.dataset.profile);showAll=false;filter='all';closeModal();move('home');break;case'read':speak();break;case'pronounce':speak('answer');break;case'cue':speak('cue');break;case'explain':speak('explain');break;case'export':download();break;case'import':document.querySelector('#import-file').click();break;case'reload':location.reload();break;}
});
document.addEventListener('change',async e=>{if(e.target.id!=='import-file'||!e.target.files[0])return;const status=document.querySelector('#import-status');try{if(e.target.files[0].size>2000000)throw new Error('파일이 너무 커요. 배움터에서 내보낸 기록을 선택해 주세요.');Progress.importRecords(JSON.parse(await e.target.files[0].text()));render();app.inert=true;status.textContent='기록을 합쳤어요. 원래 모은 별도 그대로예요.';}catch(error){status.textContent='가져오지 못했어요. '+(error instanceof SyntaxError?'올바른 JSON 기록 파일을 골라 주세요.':error.message);}e.target.value='';});
document.addEventListener('keydown',e=>{if(!modal)return;if(e.key==='Escape')closeModal();if(e.key==='Tab'){const list=[...document.querySelector('#modal').querySelectorAll('button,a[href]')],first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
window.addEventListener('pageshow',()=>{if(catalog.length&&!modal)render();});
window.addEventListener('storage',e=>{if(e.key===Progress.LEARNER_KEY){if(modal)closeModal();showAll=false;filter='all';move('home');return;}if([Progress.KEY,Progress.LEGACY_KEY].includes(e.key)&&!modal)render();});
try{catalog=await loadCatalog();Progress.configureCatalog(catalog);render();}catch(e){error=e.message;render();}
if(document.modelContext?.registerTool){const abort=new AbortController();const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:abort.signal})).catch(()=>{});}catch{}};
 register({name:'list_learning_games',description:'사용 가능한 학습 게임과 현재 아이의 별을 확인합니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({learner:currentLearner().name,games:published().map(g=>({id:g.id,title:g.title,subject:g.subject,kind:g.kind})),progress:overview()})});
 register({name:'filter_learning_games',description:'배움터의 과목 필터를 바꿉니다. 게임을 시작하거나 점수를 주지 않습니다.',inputSchema:{type:'object',properties:{subject:{type:'string',enum:Object.keys(SUBJECTS)}},required:['subject'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!Object.hasOwn(SUBJECTS,input.subject)||Object.keys(input).some(k=>k!=='subject'))throw new Error('유효한 과목을 선택해 주세요.');filter=input.subject;move('home');return{subject:filter,games:published().filter(g=>filter==='all'||g.subject===filter).map(g=>g.id)};}});
 window.addEventListener('pagehide',()=>abort.abort(),{once:true});
}
