/** Accessible tap-based activities. All visible data passes through the caller's esc(). */
export const MODE_LABELS={choice:'골라요',build:'쌓아요',sequence:'순서 놀이',match:'짝 놀이',memory:'기억 놀이'};
const shuffled=n=>{const a=Array.from({length:n},(_,i)=>i);for(let i=n-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
export function createDraft(q){const i=q.interaction;return !i||i.type==='choice'?null:i.type==='build'?{amount:0}:i.type==='match'?{left:null,pairs:Array(i.left.length).fill(null),rightOrder:shuffled(i.right.length)}:{selected:[],revealed:i.type==='memory',tileOrder:shuffled(i.items.length)};}
export function draftResponse(q,d){if(!q.interaction)return null;return q.interaction.type==='build'?d.amount:q.interaction.type==='match'?d.pairs:[...d.selected];}
export function ready(q,d){const i=q.interaction;if(!i)return false;if(i.type==='build')return true;if(i.type==='match')return d.pairs.every(v=>Number.isInteger(v));return !d.revealed&&d.selected.length===i.items.length;}
export function interact(q,d,action,index){const i=q.interaction;if(!i||!d)return;
 if(action==='activity-plus'&&i.type==='build')d.amount=Math.min(i.max,d.amount+1);
 if(action==='activity-minus'&&i.type==='build')d.amount=Math.max(0,d.amount-1);
 if(action==='activity-tile'&&['sequence','memory'].includes(i.type)&&!d.revealed&&index>=0&&index<i.items.length&&!d.selected.includes(index))d.selected.push(index);
 if(action==='activity-undo'&&['sequence','memory'].includes(i.type))d.selected.pop();
 if(action==='activity-reset'){if(i.type==='build')d.amount=0;else if(i.type==='match'){d.left=null;d.pairs.fill(null);}else d.selected=[];}
 if(action==='activity-remember'&&i.type==='memory'){d.revealed=false;d.selected=[];}
 if(action==='activity-reveal'&&i.type==='memory'){d.revealed=true;d.selected=[];}
 if(action==='activity-left'&&i.type==='match'&&index>=0&&index<i.left.length)d.left=index;
 if(action==='activity-right'&&i.type==='match'&&d.left!==null&&index>=0&&index<i.right.length){const previous=d.pairs.indexOf(index);if(previous>=0)d.pairs[previous]=null;d.pairs[d.left]=index;d.left=null;}
}
export function renderActivity(q,a,d,esc){const i=q.interaction;
 if(!i||i.type==='choice')return `<div class="answers ${q.choiceMode==='picture'?'picture-answers':''}" aria-label="정답 고르기">${q.choices.map((choice,n)=>`<button class="answer ${a?(n===q.answer?'correct':n===(a.choice??a.response)?'wrong':''):''}" data-action="answer" data-choice="${n}" ${q.choiceLabels?`aria-label="${esc(q.choiceLabels[n])}"`:''} ${a?'disabled':''}><span class="answer-num">${a&&n===q.answer?'✓':n+1}</span><span>${esc(choice)}</span></button>`).join('')}</div>`;
 if(a)return `<p class="submitted-note">내 생각을 확인했어. 아래 해설을 만나 보자!</p>`;
 let body='';
 if(i.type==='build')body=`<div class="build-tray" role="img" aria-label="지금 ${d.amount}${esc(i.unit)}"><div class="build-items">${d.amount?Array.from({length:d.amount},()=>`<span aria-hidden="true">${esc(i.emoji)}</span>`).join(''):'<span class="empty-tray">여기에 하나씩 담아 봐!</span>'}</div></div><div class="build-controls"><button data-action="activity-minus" aria-label="하나 빼기" ${d.amount===0?'disabled':''}>−</button><output aria-live="polite">${d.amount}<small>${esc(i.unit)}</small></output><button data-action="activity-plus" aria-label="하나 더하기" ${d.amount===i.max?'disabled':''}>+</button></div>`;
 else if(i.type==='match')body=`<p class="activity-tip">왼쪽 하나, 오른쪽 하나를 눌러 연결해요.</p><div class="match-board"><div>${i.left.map((text,n)=>`<button class="match-tile ${d.left===n?'picked':''} ${d.pairs[n]!==null?'linked':''}" data-action="activity-left" data-index="${n}" aria-pressed="${d.left===n}" ${i.leftLang?`lang="${esc(i.leftLang)}"`:''}><span class="pair-badge">${n+1}</span>${esc(text)}</button>`).join('')}</div><div>${d.rightOrder.map(n=>`<button class="match-tile ${d.pairs.includes(n)?'linked':''}" data-action="activity-right" data-index="${n}" ${i.rightLabels?`aria-label="${esc(i.rightLabels[n])}, ${d.pairs.includes(n)?(d.pairs.indexOf(n)+1)+'번과 연결됨':'연결 전'}"`:''}><span class="pair-badge">${d.pairs.includes(n)?d.pairs.indexOf(n)+1:'·'}</span>${esc(i.right[n])}</button>`).join('')}</div></div>`;
 else if(i.type==='memory'&&d.revealed)return `<section class="activity"><p class="activity-tip">순서를 기억해요. 준비되면 가려 봐요.</p><div class="memory-preview">${i.order.map((n,k)=>`<div><small>${k+1}</small><span ${i.itemLabels?`role="img" aria-label="${esc(i.itemLabels[n])}"`:''}>${esc(i.items[n])}</span></div>`).join('')}</div><button class="primary" data-action="activity-remember">기억했어요!</button></section>`;
 else body=`<p class="activity-tip">${i.type==='memory'?'기억한 순서대로 그림을 눌러요.':'먼저 올 것부터 차례로 눌러요.'}</p><ol class="sequence-slots" aria-label="내가 놓은 순서">${Array.from({length:i.items.length},(_,n)=>`<li class="${d.selected[n]!==undefined?'filled':''}"><small>${n+1}</small><span>${d.selected[n]!==undefined?esc(i.items[d.selected[n]]):'?'}</span></li>`).join('')}</ol><div class="sequence-tiles">${d.tileOrder.map(n=>`<button data-action="activity-tile" data-index="${n}" ${d.selected.includes(n)?'disabled':''} ${i.itemLabels?`aria-label="${esc(i.itemLabels[n])}"`:''}>${esc(i.items[n])}</button>`).join('')}</div><div class="activity-tools"><button class="text-button" data-action="activity-undo" ${!d.selected.length?'disabled':''}>하나 되돌리기</button>${i.type==='memory'?'<button class="text-button" data-action="activity-reveal">다시 살펴보기</button>':''}</div>`;
 return `<section class="activity" data-activity="${i.type}">${body}<button class="primary" data-action="activity-submit" ${ready(q,d)?'':'disabled'}>이렇게 할래요!</button>${i.type==='build'||i.type==='match'?'<button class="text-button" data-action="activity-reset">다시 놓기</button>':''}</section>`;
}
