/** Permanent digital gifts and parent-confirmed family requests.
 * Existing IDs and prices remain stable so old receipts stay valid. */
export const REWARD_CATEGORIES=Object.freeze([
 {id:'light',title:'빛 장식',emoji:'✨'},
 {id:'background',title:'배경',emoji:'🎨'},
 {id:'friend',title:'동물 친구',emoji:'🐰'},
 {id:'mark',title:'응원 마크',emoji:'🌼'},
 {id:'title',title:'이름표',emoji:'🏷️'},
 {id:'family',title:'가족 활동',emoji:'🏡'}
].map(Object.freeze));
const gift=(id,category,cost,title,description,emoji,extra={})=>Object.freeze({id,category,kind:category==='family'?'family':'cosmetic',cost,title,description,emoji,...extra});
export const REWARD_ITEMS=Object.freeze([
 gift('sun-spark','light',10,'햇살 반짝이','요정 곁에 노란 별 여섯 개가 반짝여요.','☀️',{effect:{color:0xffbf39,count:6}}),
 gift('mint-gems','light',25,'민트 보석빛','작은 보석들이 민트빛으로 빙글 돌아요.','💎',{effect:{color:0x39bfa1,count:5,gemScale:0.09}}),
 gift('trail-stars','light',30,'반짝 별 꼬리','요정 뒤에 작은 별이 따라와요.','✨',{effect:{count:9}}),
 gift('coral-orbit','light',35,'살구빛 궤도','따뜻한 살구빛 고리가 요정을 감싸요.','🟠',{effect:{color:0xff9674,count:7,ring:true}}),
 gift('ocean-stars','light',55,'바다 별빛','푸른 별들이 요정 주변을 천천히 돌아요.','💙',{effect:{color:0x4b9ce2,count:8,speed:0.3}}),
 gift('halo','light',60,'빛나는 꽃 고리','요정 머리 위에 꽃빛이 떠올라요.','🌸',{effect:{halo:true}}),
 gift('rainbow-orbit','light',80,'무지개 별빛','알록달록한 별들이 요정을 감싸요.','🌈',{effect:{rainbow:true,count:9,ring:true}}),
 gift('comet','light',100,'혜성 날개','요정이 혜성빛을 펼쳐요.','☄️',{effect:{comet:true}}),
 gift('galaxy-glow','light',110,'은하수 반짝임','보라빛 별과 혜성이 함께 반짝여요.','🌌',{effect:{color:0x9470ef,count:9,halo:true,comet:true}}),
 gift('bg-sky','background',20,'하늘빛 배움터','배움터 배경을 맑은 하늘빛으로 꾸며요.','🩵',{colors:['#e3f4ff','#f5fbff']}),
 gift('bg-leaf','background',25,'새싹빛 배움터','배움터 배경을 연두빛으로 꾸며요.','🌱',{colors:['#e8f8dc','#f7fcf1']}),
 gift('bg-peach','background',25,'복숭아빛 배움터','배움터 배경을 따뜻한 복숭아빛으로 꾸며요.','🍑',{colors:['#ffe7dc','#fff8f3']}),
 gift('bg-ocean','background',35,'바다빛 배움터','배움터 배경을 시원한 바다빛으로 꾸며요.','🌊',{colors:['#dff7f3','#f4fcfb']}),
 gift('bg-lemon','background',20,'레몬빛 배움터','배움터 배경을 환한 레몬빛으로 꾸며요.','🍋',{colors:['#fff7d4','#fffdf3']}),
 gift('bg-lilac','background',40,'라일락빛 배움터','배움터 배경을 포근한 보라빛으로 꾸며요.','💜',{colors:['#ece3fc','#faf7ff']}),
 gift('bg-rose','background',40,'장미빛 배움터','배움터 배경을 다정한 분홍빛으로 꾸며요.','🌷',{colors:['#ffe3ed','#fff6fa']}),
 gift('bg-rainbow','background',70,'무지개빛 배움터','배움터 배경에 여러 색이 함께 어울려요.','🌈',{colors:['#e7f4ff','#fff0db','#f0e6ff']}),
 gift('friend-rabbit','friend',15,'토끼 친구','토끼가 요정 곁에서 배움을 함께해요.','🐰'),
 gift('friend-cat','friend',20,'고양이 친구','고양이가 요정 곁에서 배움을 함께해요.','🐱'),
 gift('friend-bear','friend',30,'곰 친구','곰이 요정 곁에서 배움을 함께해요.','🐻'),
 gift('friend-fox','friend',35,'여우 친구','여우가 요정 곁에서 배움을 함께해요.','🦊'),
 gift('friend-owl','friend',45,'부엉이 친구','부엉이가 요정 곁에서 배움을 함께해요.','🦉'),
 gift('friend-butterfly','friend',40,'나비 친구','나비가 요정 곁에서 배움을 함께해요.','🦋'),
 gift('friend-penguin','friend',50,'펭귄 친구','펭귄이 요정 곁에서 배움을 함께해요.','🐧'),
 gift('friend-whale','friend',65,'고래 친구','고래가 요정 곁에서 배움을 함께해요.','🐳'),
 gift('mark-flower','mark',10,'꽃 응원 마크','요정 옆에 꽃 마크를 달아요.','🌼'),
 gift('mark-leaf','mark',15,'새싹 응원 마크','요정 옆에 새싹 마크를 달아요.','🌱'),
 gift('mark-ribbon','mark',20,'리본 응원 마크','요정 옆에 리본 마크를 달아요.','🎀'),
 gift('mark-heart','mark',25,'하트 응원 마크','요정 옆에 하트 마크를 달아요.','💗'),
 gift('mark-clover','mark',30,'네잎클로버 마크','요정 옆에 클로버 마크를 달아요.','🍀'),
 gift('mark-cherry','mark',20,'체리 응원 마크','요정 옆에 체리 마크를 달아요.','🍒'),
 gift('mark-moon','mark',35,'달 응원 마크','요정 옆에 초승달 마크를 달아요.','🌙'),
 gift('mark-palette','mark',40,'알록달록 응원 마크','요정 옆에 팔레트 마크를 달아요.','🎨'),
 gift('title-curious','title',10,'궁금한 탐험가','요정 아래에 이름표를 달아요.','🔎',{label:'궁금한 탐험가'}),
 gift('title-number','title',20,'숫자 여행자','요정 아래에 숫자 여행자 이름표를 달아요.','🔢',{label:'숫자 여행자'}),
 gift('title-word','title',20,'낱말 수집가','요정 아래에 낱말 수집가 이름표를 달아요.','📚',{label:'낱말 수집가'}),
 gift('title-hello','title',25,'인사 여행자','요정 아래에 인사 여행자 이름표를 달아요.','👋',{label:'인사 여행자'}),
 gift('title-thinker','title',30,'생각 정원사','요정 아래에 생각 정원사 이름표를 달아요.','🌻',{label:'생각 정원사'}),
 gift('title-maker','title',35,'상상 발명가','요정 아래에 상상 발명가 이름표를 달아요.','💡',{label:'상상 발명가'}),
 gift('title-story','title',40,'이야기 작가','요정 아래에 이야기 작가 이름표를 달아요.','✏️',{label:'이야기 작가'}),
 gift('title-space','title',55,'별빛 모험가','요정 아래에 별빛 모험가 이름표를 달아요.','🚀',{label:'별빛 모험가'}),
 gift('story','family',40,'함께 이야기 읽기','보호자에게 함께 읽을 시간을 부탁해요.','📖'),
 gift('drawing','family',45,'함께 그림 그리기','보호자와 함께 그릴 주제와 시간을 정해요.','🖍️'),
 gift('paperfold','family',60,'함께 종이접기','보호자와 접고 싶은 모양을 함께 정해요.','🧩'),
 gift('walk','family',80,'함께 산책하기','보호자와 산책할 날을 함께 정해요.','🌳'),
 gift('experiment','family',90,'함께 작은 실험','보호자와 안전한 놀이 실험을 골라요.','🔬'),
 gift('cooking','family',100,'함께 간식 만들기','보호자와 만들 수 있는 간식을 의논해요.','🥣'),
 gift('picnic','family',120,'함께 소풍 계획하기','보호자와 작은 소풍을 의논해요.','🧺')
]);
export const OUTFIT_SLOTS=Object.freeze(['background','friend','mark','title']);
